name: Ruff Check (UV)

on:
  pull_request:
    branches:
      - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and reviewdog
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv venv
          uv pip install 'ruff>=0.1.3'
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin

      - name: Run Ruff and report via reviewdog
        run: |
          uv run ruff check . --format=json \
            | ./bin/reviewdog -f=ruff -name=ruff -reporter=github-pr-review -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
