name: Ruff Check (UV)

on:
  pull_request:
    branches:
      - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create uv environment and install ruff
        run: |
          uv venv
          uv pip install ruff

      - name: Run Ruff check
        run: uv run ruff check .
