name: Ruff Check

on:
  pull_request:
    branches:
      - "main"
      - "staging"

jobs:
  ruff:
    name: Ruff + Reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff and Reviewdog
        run: |
          pip install ruff
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin

      - name: Run Ruff with Reviewdog
        run: |
          ruff check . --format=github \
          | ./bin/reviewdog -f=github-pr-review \
              -name="ruff" \
              -reporter=github-pr-review \
              -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
