name: Ruff Check (UV)

on:
  pull_request:
    branches:
      - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv and ruff
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          ~/.cargo/bin/uv pip install ruff

      - name: Run Ruff check
        run: ~/.cargo/bin/uv run ruff check .
